### PR TITLE
[FLAG-685] Planet obscures data layers

### PR DESCRIPTION
**Pull request by SARodrigues**
## Overview

This is a test branch to debug a possible dataset misconfiguration that causes layers to disappear in a very particular scenario. Notes on how to reproduce the original bug below. 

## Bug

- When Planet imagery is displayed with any other dataset, we’re finding that toggling PTW will cause that dataset to disappear. It will appear if that dataset is toggled on after PTW is toggled on or if the datasets are rearranged in the legend.
- When Planet is displayed, the PTW icons disappear when zooming in past zoom level 8. 
- Occurs across the following browsers: Edge, Edge in Private, Chrome, and Chrome incognito.

## Notes  

The layer configuration changes that seem to fix the bug can be found here: https://github.com/Vizzuality/gfw/pull/4533/commits/10065b93de5470ff0c3929f9a471f9e945f5db88 .
At the moment, this PR has mocked datasets in order to allow us to test the bug resolution. 

## Tracking

[FLAG-685 | Planet obscures data layers](https://gfw.atlassian.net/browse/FLAG-685)

## Testing

[Direct link to the a setup to replicate the bug](https://gfw-staging-pr-4533.herokuapp.com/map/?map=eyJjZW50ZXIiOnsibGF0IjotOS40NzcwNDUxNzMwNTU0NzMsImxuZyI6LTc1LjUxMjg3NjkyNDcxNDU1fSwiem9vbSI6MTEuMzA2MDQxMTUwMjg2NDYsImJhc2VtYXAiOnsidmFsdWUiOiJwbGFuZXQiLCJjb2xvciI6IiIsIm5hbWUiOiJwbGFuZXRfbWVkcmVzX25vcm1hbGl6ZWRfYW5hbHl0aWNfMjAyMy0wMl9tb3NhaWMiLCJpbWFnZVR5cGUiOiJhbmFseXRpYyJ9LCJkYXRhc2V0cyI6W3siZGF0YXNldCI6InBvbGl0aWNhbC1ib3VuZGFyaWVzIiwibGF5ZXJzIjpbImRpc3B1dGVkLXBvbGl0aWNhbC1ib3VuZGFyaWVzIiwicG9saXRpY2FsLWJvdW5kYXJpZXMiXSwib3BhY2l0eSI6MSwidmlzaWJpbGl0eSI6dHJ1ZX0seyJkYXRhc2V0IjoiZ2xhZC1kZWZvcmVzdGF0aW9uLWFsZXJ0cy12MiIsIm9wYWNpdHkiOjEsInZpc2liaWxpdHkiOnRydWUsImxheWVycyI6WyJwbGFjZXMtdG8td2F0Y2gtdjIiXX0seyJkYXRhc2V0IjoiaW50ZWdyYXRlZC1kZWZvcmVzdGF0aW9uLWFsZXJ0cy04Yml0Iiwib3BhY2l0eSI6MSwidmlzaWJpbGl0eSI6dHJ1ZSwibGF5ZXJzIjpbImludGVncmF0ZWQtZGVmb3Jlc3RhdGlvbi1hbGVydHMtOGJpdCJdfSx7ImRhdGFzZXQiOiJsYW5kbWFyayIsIm9wYWNpdHkiOjEsInZpc2liaWxpdHkiOnRydWUsImxheWVycyI6WyJpbmRpZ2Vub3VzLWFuZC1jb21tdW5pdHktbGFuZHMtMjAxOSJdfV19&mapMenu=eyJkYXRhc2V0Q2F0ZWdvcnkiOiJsYW5kVXNlIn0%3D)

### CODE REVIEW

**Comment by SARodrigues** [comment]
Removed the mocked datasets & dataset test changes. 
No longer needed - changes implemented upstream by the science team.

**Comment by AngelArcones** [comment]
Testing the updates, all of them work as intended and respond to different configurations.

**Review by AngelArcones — COMMENTED** [review]
Testing the updates, all of them work as intended and respond to different configurations.

**Comment by SARodrigues** [comment]
@AngelArcones Thank you so much for taking a look!

**Pull request merged**
