### PR TITLE
updated data policy text & fixed misspelled words

### PR DESCRIPTION
**Pull request by alyssaw**

### CODE REVIEW

**Comment by alyssaw** [comment]
@d4weed @apercas @mbarrenechea Never mind!  I see it has been merged, just not deployed... Sorry!

**Comment by alyssaw** [comment]
@d4weed @apercas @mbarrenechea Can we deploy this to PRO?

**Comment by alyssaw** [comment]
@d4weed @apercas @mbarrenechea Hey guys - this still needs to be deployed to PRO.  Can we please do this ASAP?

**Comment by apercas** [comment]
@alyssaw Hi, I've checked the mangrove part of the file and it's deployed to PRO. Which part are you missing? Thank you.

**Comment by alyssaw** [comment]
@apercas The data policy still refers to the MIT license and not the CC by 4.0

**Pull request merged**
