### PR TITLE
[Fix, not urgent] Fixed downloads for GLAD and VIIRS alerts on the map legend

### PR DESCRIPTION
**Pull request by blayhem**
## Overview

Updated the widget header component to show the download button _also_ for widgets in the map legend so everybody can download data for the widgets directly from there. This allows downloads for GLAD and VIIRS datasets from the map, and more.

### CODE REVIEW

**Comment by sorodrigo** [comment]
dont comment code, we have version control to do this.

**Comment by aabdaab** [comment]
checking! 👀

**Comment by aabdaab** [comment]
1. why not checking out from develop so develop can be in sync as well?
2. let's make a pair-code review or rather a functionality review.. I'm not entirely sure which parts should I be checking here ☝️#gfw-n00b
let's do it on Monday morning if you will

**Comment by sorodrigo** [comment]
I think it did affected all other layers that aren’t GLAD and VIIRS and we said it wasn’t ready.

P.S. is there a way to remove me from the PR? 😅

**Pull request merged**
